apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT/BE_IMAGE
    newName: mluukkai/the-todo-backend:10
resources:
  - manifests/ingress.yaml
  - manifests/db_deployment.yaml
  - manifests/backend/deployment.yaml
  - manifests/backend/service.yaml
  - manifests/backend/configmap.yaml