apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: project-data
          persistentVolumeClaim:
            claimName: todo-app-claim    
      containers:
        - name: todo-app
          image: PROJECT/APP_IMAGE
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-generic-conf
                  key: BACKEND_URL
          volumeMounts:
            - mountPath: /app/pics
              name: project-data
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
            requests:
              cpu: "015"
              memory: "256Mi"