apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-claim
  namespace: project
spec:
  storageClassName: project-image
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
