name: Deploy application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-clster
  GKE_ZONE: europe-north1-b
  BE_IMAGE: todo-backend
  APP_IMAGE: todo-app
  CRON_IMAGE: todo-cron
  NAMESPACE: ${{ github.ref_name == 'main' && 'default' || github.ref_name }}
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - run: kubectl version

      - name: Build backend
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$BE_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" ./backend

      - name: Publish backend
        run: |-
          docker push "gcr.io/$PROJECT_ID/$BE_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Build app
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$APP_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" ./app

      - name: Publish app
        run: |-
          docker push "gcr.io/$PROJECT_ID/$APP_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Build cron
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$CRON_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" ./cron

      - name: Publish cron
        run: |-
          docker push "gcr.io/$PROJECT_ID/$CRON_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: print namespace
        run: echo using namespace $NAMESPACE

      - name: print stuff
        run: |- 
          echo "${GITHUB_REF#refs/heads/}"
          echo "${BRANCH}"

      - name: Deploy
        run: |-   
          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image PROJECT/BE_IMAGE=gcr.io/$PROJECT_ID/$BE_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize edit set image PROJECT/APP_IMAGE=gcr.io/$PROJECT_ID/$APP_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize edit set image PROJECT/CRON_IMAGE=gcr.io/$PROJECT_ID/$CRON_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment todo-backend-dep todo-app-dep
          kubectl get services -o wide